### ISSUE TITLE
想学习下图片中的有3D部分的项目，能放吗？

### ISSUE THREAD

**Issue by saywol** [Mario343214420/Big-Data-Demo#36]
想学习下图片中的有3D部分的项目，能放吗？

**Comment by Mario343214420** [comment]
three_for_channel分支，对应模型文件较大，未上传，https://sketchfab.com/这里可以下载模型资源，应用的threeJS库

**Comment by JaneYork** [comment]
> three_for_channel分支，对应模型文件较大，未上传，[https://sketchfab.com/这里可以下载模型资源，应用的threeJS库](https://sketchfab.com/%E8%BF%99%E9%87%8C%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E6%A8%A1%E5%9E%8B%E8%B5%84%E6%BA%90%EF%BC%8C%E5%BA%94%E7%94%A8%E7%9A%84threeJS%E5%BA%93)

方便上传个云盘吗 ，移动云 ，阿里云盘，都不限速

**Comment by Mario343214420** [comment]
> > three_for_channel分支，对应模型文件较大，未上传，[https://sketchfab.com/这里可以下载模型资源，应用的threeJS库](https://sketchfab.com/%E8%BF%99%E9%87%8C%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E6%A8%A1%E5%9E%8B%E8%B5%84%E6%BA%90%EF%BC%8C%E5%BA%94%E7%94%A8%E7%9A%84threeJS%E5%BA%93)
> 
> 方便上传个云盘吗 ，移动云 ，阿里云盘，都不限速。完整模型或者离线包，模型名称是什么呢sketchfab上 @Mario343214420

不方便上传项目模型，您可以在sketchfab中找免费可下载的
